spring:
  datasource:
    username: root
    password: YYH19981108
    url: jdbc:mysql://127.0.0.1:3306/fresh?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
